title: "David S. Batista"
tagline: ""
description: "Ph.D., Natural Language Processing, Machine Learning"
baseurl: ""
url: "http://www.davidsbatista.net/"
email: dsbatista@gmail.com
twitter_username: DavidSBatista
github_username:  davidsbatista
linkedin_link: http://linkedin.com/in/dsbatista
stackoverflow: 4324153/david-batista
gscholar: -tRNGd0AAAAJ
researchgate: David_Batista4
timezone: Europe/Berlin

markdown: kramdown
permalink: pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons/"

pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 100
  offset: 0
  # permalink: '/blog/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
