title: David S. Batista
#tagline: ""
description: "Ph.D., Natural Language Processing, Machine Learning, Big-Data"
baseurl: ""
url: "http://www.davidsbatista.net"
email: dsbatista@gmail.com
twitter_username: DavidSBatista
github_username:  davidsbatista
linkedin_link: http://linkedin.com/in/dsbatista
stackoverflow: 4324153/david-batista
gscholar: -tRNGd0AAAAJ
researchgate: David_Batista4
timezone: Europe/Berlin

markdown: kramdown
#markdown: redcarpet
permalink: pretty
#excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

#lsi: true

# Gems
plugins: [jekyll-paginate, jekyll-sitemap]

paginate: 10
paginate_path: "blog/p:num"
